<a href="https://colab.research.google.com/github/AadityaAdh/tf_RaggedTensors/blob/main/Ragged_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

#tensorflow types


#Ragged tensors

when a matrix is non rectangular

vanya yeuta rowma dherai element aarko ma thorai

tf.constant lae jailae ni rectangular tensor nai magxa

so use tf.ragged.constant(your tensor)

In [ ]:
ragged_matrix=np.array([[1,2,3,4],
                        [5],
                        [6,7,8,9,10,11,12,13,14]])
ragged_matrix

<ipython-input-4-5e8d73359bd8>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ragged_matrix=np.array([[1,2,3,4],


array([list([1, 2, 3, 4]), list([5]),
       list([6, 7, 8, 9, 10, 11, 12, 13, 14])], dtype=object)

In [ ]:
tf.constant(ragged_matrix)
#so error here


ValueError: ignored

In [ ]:
tf.ragged.constant(ragged_matrix)

<tf.RaggedTensor [[1, 2, 3, 4], [5], [6, 7, 8, 9, 10, 11, 12, 13, 14]]>

In [ ]:
#aaba shape garda columns ma none aauxa
#as no of columns is differernt
tf.ragged.constant(ragged_matrix).shape

TensorShape([3, None])

#Masking

yedi kunai element lai nikalnu paryo vanae masking garinxa

tf.ragged.boolean_mask


Applies a boolean mask to data without flattening the mask dimensions.

tf.ragged.boolean_mask(
    data, mask, name=None
)

mask vanya tei pattern ma true false lekhiyae ko

[[T,F,T],[T,T,T]]
yesto garae ko





In [ ]:
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[False, False, True], [False], [True, True]]))


<tf.RaggedTensor [[3], [], [5, 6]]>

yestai gari yedi kunai channel hataunu paryo or channel vitra ko kei hataunu paryo vanae kaam lagxa

In [ ]:
#lets delete a channel

t1_in3d=tf.constant(np.arange(1,28),shape=[3,3,3])
t1_in3d

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [ ]:
#lets delete the first channel
tf.ragged.boolean_mask(t1_in3d,tf.ragged.constant([False, True, True]))

<tf.Tensor: shape=(2, 3, 3), dtype=int64, numpy=
array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

#creating new matrix from a row

tf.RaggedTensor.from_row_lengths(


    values, row_lengths, name=None, validate=True
)

note:yaa raggedtensor xa not only ragged like up


values vanya your any row
row length vanya array:[4,3,1,0]


first 4 elmeents ko yeuta row


then next 3 ko yeuta row.... and so on

note:output will be a array or matrix which is non rectangular
so you can only use with ragged tensor

In [ ]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))


<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
